ENH: add verbose param to to_data_frame methods
mne-tools/mne-python pull request #10140
Opened 2021-12-15 16:31 UTC by sappelhoff

When calling `.to_data_frame` on a number of objects in a loop, the output can get quite verbose. Here I add the `verbose` decorator to the function calls where appropriate (I hope).

The logging that gets too spammy happens in `_set_pandas_dtype`.

2021-12-15 17:16 UTC, larsoner requested changes

2021-12-15 17:16 UTC, larsoner commented on mne/epochs.py
>      @fill_doc
`@verbose` does a `@fill_doc` under the hood so you can remove this
```suggestion
    @verbose
```

2021-12-15 17:16 UTC, larsoner commented on mne/epochs.py
>              .. versionadded:: 0.20
Keep the versionadded with the `df_time_format` param
```suggestion

            .. versionadded:: 0.20
        %(verbose)s

            .. versionadded:: 1.0
```
You could add one for `verbose`, too, but we sometimes don't bother for that `kwarg`

2021-12-15 17:16 UTC, larsoner commented on mne/epochs.py
> +                               verbose=verbose)
There should be no need to pass this param to `_build_data_frame` based on how the magic of `verbose` works
```suggestion
                               default_index=['condition', 'epoch', 'time'])
```

2021-12-15 17:16 UTC, larsoner commented on mne/evoked.py
> +    @verbose
same stuff in this file and the others

2021-12-16 10:07 UTC, sappelhoff reviewed
Thanks @larsoner I think I addressed all your points. I added one thing: I thought it was a good idea to make the parameters before "verbose" keyword only, so that we can more easily add additional kwargs in the future and keep verbose as the last kwarg without breaking backward compatibility. WDYT about that?

2021-12-16 15:42 UTC, merged

2021-12-16 15:42 UTC, larsoner commented
Thanks @sappelhoff !