Allow silencing of "The unit for channel(s) ... has changed" warnings
mne-tools/mne-python pull request #11668
Opened 2023-04-29 10:32 UTC by hoechenberger

In MNE-BIDS we commonly change the units during an ordinary reading operation. This is expected behavior and should not yield a warning.

However, trying to catch and filter the warning MNE emits is quite cumbersome, esp. inside the MNE-BIDS test suite.

I therefore believe the best approach is to allow silencing of the warnings in MNE-Python directly.

This PR adds a new parameter, `on_unit_change`, to the `.set_channel_types()` methods. The default is to warn, but users can
now also choose to `'ignore'` this.

x-ref https://github.com/mne-tools/mne-bids/issues/1100

2023-04-30 13:23 UTC, hoechenberger commented
CI failures seem unrelated

2023-04-30 13:27 UTC, hoechenberger commented
Note that in the few tests where I removed the `pytest.warns()` context managers, I made sure those tests were not designed to actually test for those warnings – the warnings simply had to be caught to prevent the tests of some other functionality from failing. The tests that **do** focus on the warnings still remain in the test suite.

2023-04-30 15:33 UTC, hoechenberger commented on mne/channels/channels.py
> +            channels is changed automatically to match the new sensor
```suggestion
            channel is changed automatically to match the new sensor
```

2023-05-01 00:44 UTC, larsoner requested changes

2023-05-01 00:44 UTC, larsoner commented on mne/channels/channels.py
> +        )
I don't see a reason not to allow `raise`. And if we do that we might as well use our standard `on_*` helpers. This should make the code more DRY

2023-05-01 10:08 UTC, hoechenberger commented
Style Check error seems unrelated

2023-05-01 11:20 UTC, hoechenberger commented
I believe the CI errors are unrelated

2023-05-01 16:36 UTC, merged

2023-05-01 16:36 UTC, larsoner commented
Thanks @hoechenberger !