Update affiliation
mne-tools/mne-python pull request #11695
Opened 2023-05-14 03:37 UTC by rob-luke

I have moved from MQ to AE. In addition to my contributions, AE itself has begun contributing PRs to MNE (e.g. #11662, #9575, https://github.com/mne-tools/mne-nirs/pull/511, and more to come!)

2023-05-14 06:49 UTC, agramfort approved these changes

2023-05-14 07:33 UTC, rob-luke commented
The scaling is still a tad small. But I think it’s a close enough match to the others. Please merge if you’re happy @larsoner @drammock

2023-05-15 13:55 UTC, drammock requested changes

2023-05-16 06:04 UTC, rob-luke commented on doc/conf.py
> +            size=xxl,
I added MQ back. Thanks @drammock

2023-05-16 07:58 UTC, hoechenberger approved these changes

2023-05-16 12:36 UTC, drammock approved these changes

2023-05-16 12:36 UTC, merged