adding unify channels to preprocessing draft
mne-tools/mne-python pull request #12014
Opened 2023-09-25 18:45 UTC by anaradanovic

Thanks for contributing a pull request! Please make sure you have read the
[contribution guidelines](https://mne.tools/dev/install/contributing.html)
before submitting.

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

#### Reference issue
Example: Fixes #1234.

#### What does this implement/fix?
Explain your changes.

#### Additional information
Any additional information you think is important.

2023-09-25 19:58 UTC, drammock commented on mne/preprocessing/unify_bads.py
> +
```suggestion
    all_bads = dict()
    for inst in insts:
        all_bads.update(dict.fromkeys(inst.info['bads']))
    all_bads = list(all_bads)
```

2023-09-25 19:58 UTC, drammock commented on mne/preprocessing/unify_bads.py
> +
reminder to put in an explanatory comment about why we're using a dict here

2023-09-27 19:15 UTC, drammock requested changes
looks good so far, see comments below.

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +        raise ValueError(f"insts must be a *list* of mne objects, got {type(insts)}")
this goes away, replaced by an additional call to `_validate_type(..., list)` at the very beginning.

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +    ch_names = insts[0].info.ch_names
```suggestion
    ch_names = insts[0].ch_names
```

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +        if inst.info.ch_names != ch_names:
```suggestion
        if inst.ch_names != ch_names:
```

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +        if inst.info.ch_names != ch_names:
check the set(ch_names) equality first, if the sets are the same but the orders are different, give an appropriate error msg. Error msgs should reference how to fix it (e.g., `equalize_channels` func)

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +    """
add a `See Also` section with crossrefs to `equalize_channels` etc.

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +    # then iterate through the insts to gather bads
```suggestion
    # collect bads as dict keys so that insertion order is preserved
    # then later cast to list.
```

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +        # using dictionary method to remove duplicates & preserve order
```suggestion
```

2023-09-27 19:15 UTC, drammock commented on mne/preprocessing/bads.py
> +    return new_insts
modify in-place and return original list (`inst`), no need for `new_inst`

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +        )
```suggestion
    for inst in insts[1:]:
        dif = set(inst.ch_names) ^ set(ch_names)
        if len(dif):
            # TODO raise error, we know some chs need to be dropped
            raise ValueError("")
        elif inst.ch_names != ch_names:
            raise ValueError(
                "Channel names are sorted differently across instances. Please use "
                "mne.channels.equalize_channels."
            )
```
this refactor does 2 things:

1. fail early / don't bother checking all insts if we know at least one is mismatched
2. reduces cyclomatic complexity (i.e., number of intents from for/if/while clauses), which makes the code easier to read  and reason about

2023-09-27 21:15 UTC, drammock commented on mne/preprocessing/bads.py
> +#
```suggestion
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +
```suggestion
    """Unify bad channels across a list of instances.

    All instances must be of the same type and have matching channel names and channel
    order. The ``.info["bads"]`` of each instance will be set to the union of
    ``.info["bads"]`` across all instances.
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # check that input is a list
```suggestion
    # ensure input is list-like
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # check input is not an empty list
```suggestion
    # ensure non-empty
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # first check that each object is mne object
```suggestion
    # ensure all insts are MNE objects, and all the same type
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # check that all channels have the same name and same number
```suggestion
    # ensure all insts have the same channels and channel order
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # then later cast to list.
```suggestion
    # collect bads as dict keys so that insertion order is preserved, then cast to list
```

2023-09-27 21:15 UTC, drammock commented on mne/channels/channels.py
> +    # apply bads set to all instances
```suggestion
    # update bads on all instances
```

2023-09-27 21:26 UTC, drammock commented on mne/channels/channels.py
> +    Parameters
```suggestion

    Parameters
```

2023-09-27 21:42 UTC, drammock commented on mne/channels/channels.py
> +    _validate_type(insts, (list, tuple), "instance type")
```suggestion
    _validate_type(insts, (list, tuple), "insts")
```

2023-09-27 21:42 UTC, drammock commented on mne/channels/channels.py
> +        _validate_type(inst, valid_types, "instance type")
```suggestion
        _validate_type(inst, valid_types, "each object in insts")
```

2023-09-27 21:42 UTC, drammock commented on mne/channels/channels.py
> +            raise ValueError("")
```suggestion
            raise ValueError(
                "Channels do not match across the objects in insts. Consider calling "
                "equalize_channels before calling this function."
            )
```

2023-09-27 21:42 UTC, drammock commented on mne/channels/channels.py
> +        raise ValueError("Be sure insts is not empty list")
```suggestion
        raise ValueError("insts must not be empty")
```

2023-09-28 13:46 UTC, larsoner commented on mne/channels/channels.py
> +        :class:`~mne.time_frequency.EpochSpectrum`) across which to unify bad channels.
CircleCI treats warnings as errors when building docs so if you search "warning" you'll see in [the log](https://app.circleci.com/pipelines/github/mne-tools/mne-python/20948/workflows/bdb1316d-4e09-42bc-85f7-961b6d566f7a/jobs/59502):

```
/home/circleci/project/mne/channels/channels.py:docstring of mne.channels.channels.unify_bad_channels:11: WARNING: py:class reference target not found: mne.time_frequency.EpochSpectrum
```
so
```suggestion
        :class:`~mne.time_frequency.EpochsSpectrum`) across which to unify bad channels.
```

2023-09-28 19:34 UTC, drammock approved these changes

2023-09-28 19:35 UTC, drammock commented
nice work @anaradanovic and @nordme!  In it goes

2023-09-28 19:35 UTC, merged