MAINT: Post-release deprecations
mne-tools/mne-python pull request #12554
Opened 2024-04-19 18:42 UTC by larsoner

2024-04-19 19:32 UTC, larsoner commented on tools/dev/gen_css_for_mne.py
>  # Copyright the MNE-Python contributors.
Snuck in a renaming of this file -- no reason to have it in `MNE` itself as it's really a packaging tool. This helps with stuff like automated dependency resolution as well (inspired by the autotick bot's analysis on conda-forge)

2024-04-22 17:47 UTC, larsoner commented
@drammock ready for review/merge from my end

2024-04-22 18:50 UTC, drammock requested changes
looks like the version bumps in README and in GH Actions setup script aren't reflected in `pyproject.toml`?  Otherwise LGTM

2024-04-22 19:37 UTC, larsoner commented
I realized I forgot to look for stuff/workarounds we can drop now that versions are bumped!

2024-04-22 20:35 UTC, larsoner commented
Okay got a couple hundred more lines removed by getting rid of a bunch of `matplotlib` helpers that were `< 3.6` specific (and a few numpy/scipy etc. ones). Hopefully it comes back green, if it does I'll merge :crossed_fingers: !

2024-04-22 20:45 UTC, drammock commented
this should also get a changelog entry in the Dependencies section too, right?

2024-04-23 15:19 UTC, larsoner commented
@drammock okay to merge when green given the new changelog entry?

2024-04-23 15:32 UTC, drammock approved these changes

2024-04-23 20:48 UTC, merged