Enhance documentation on decimation filtering to prevent aliasing
mne-tools/mne-python pull request #12650
Opened 2024-06-06 12:41 UTC by zuazo

#### What does this implement/fix?

This update revises the **documentation** sections related to the `decim` parameter in `mne.Epochs` and the `mne.Epochs.decimate` function. It adds specific recommendations for applying a low-pass filter based on the Nyquist criterion to prevent aliasing artifacts when decimating data.

2024-06-06 14:46 UTC, drammock requested changes

2024-06-06 14:46 UTC, drammock commented on doc/help/faq.rst
> +  It is recommended to use :func:`mne.io.Raw.filter` with ``l_freq`` set to
this should be `h_freq`

2024-06-06 14:46 UTC, drammock commented on doc/help/faq.rst
> +  half the new sampling rate (fs/2N), as per the Nyquist criterion, to ensure
this should be something like "half ... or lower" or "no more than half ..."

2024-06-06 14:46 UTC, drammock commented on mne/utils/docs.py
> +                 content above this threshold.
rather than repeating these lines, I'd rather we cross-ref to the FAQ entry.

2024-06-06 15:36 UTC, zuazo commented
Thanks, @drammock, for the review. I have performed the changes you proposed. Feel free to let me know if there is any other aspect to improve.

2024-06-07 15:58 UTC, larsoner commented
@zuazo can you add a `doc/changes/devel/12650.other.rst` describing the doc update with the `:newcontrib:` and a URL for you in `doc/changes/names.inc`? See https://github.com/mne-tools/mne-python/commit/cf0e12d9e329440408b19caef974ab95a1439686 for an example

2024-06-07 16:30 UTC, zuazo commented
Sure @larsoner. Done, thank you!

2024-06-07 20:15 UTC, drammock approved these changes

2024-06-07 21:19 UTC, merged