Add `raw.rescale`
mne-tools/mne-python pull request #13018
Opened 2024-12-10 10:26 UTC by cbrnr

Fixes #12111.

2024-12-10 11:06 UTC, cbrnr commented
On a related note, could someone who uses Visual Studio Code try to debug my newly added test? Somehow, the debugger seems to be stuck when I (1) set a breakpoint in line 1070 and (2) then debug the test. Running the test does work though! Debugging tests work in other projects, so I was assuming that it's something specific to MNE. And yes, I already removed the venv and created a new one, basically using `uv venv; source .venv/bin/activate; uv pip install -e ".[test]"; uv pip install pyside6`. I also tried Python 3.13 and 3.12, and I also removed our custom pytest setup.


https://github.com/user-attachments/assets/2c5f18df-795a-4235-b65e-e854c8363bab

2024-12-10 16:26 UTC, drammock commented
> could someone who uses Visual Studio Code try to debug my newly added test?

same result as you.  I seem to be hitting https://github.com/microsoft/debugpy/issues/1623

```
./mne/io/tests/test_raw.py::test_rescale Failed: [undefined]matplotlib._api.deprecation.MatplotlibDeprecationWarning: The interactive_bk attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin(matplotlib.backends.BackendFilter.INTERACTIVE)`` instead.
mne/io/tests/test_raw.py:1070: in test_rescale
    raw = read_raw_fif(raw_fname, preload=True)  # multiple channel types
<stringsource>:69: in cfunc.to_py.__Pyx_CFunc_b0409f__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_4line.wrap
    ???
_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx:1429: in _pydevd_sys_monitoring_cython._line_event
    ???
_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx:1471: in _pydevd_sys_monitoring_cython._internal_line_event
    ???
_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx:1278: in _pydevd_sys_monitoring_cython._stop_on_breakpoint
    ???
_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx:1906: in _pydevd_sys_monitoring_cython._do_wait_suspend
    ???
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py:2197: in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, trace_suspend_type, from_this_thread, frames_tracker)
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py:2223: in _do_wait_suspend
    self._activate_gui_if_needed()
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py:1685: in _activate_gui_if_needed
    activate_function()
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py:1668: in <lambda>
    "matplotlib": lambda: activate_matplotlib(do_enable_gui),
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydev_ipython/matplotlibtools.py:99: in activate_matplotlib
    is_interactive = is_interactive_backend(backend)
/home/drmccloy/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydev_ipython/matplotlibtools.py:59: in is_interactive_backend
    from matplotlib.rcsetup import interactive_bk, non_interactive_bk  # @UnresolvedImport
/opt/mambaforge/envs/mnedev/lib/python3.12/site-packages/matplotlib/_api/__init__.py:216: in __getattr__
    return props[name].__get__(instance)
/opt/mambaforge/envs/mnedev/lib/python3.12/site-packages/matplotlib/_api/deprecation.py:161: in __get__
    emit_warning()
/opt/mambaforge/envs/mnedev/lib/python3.12/site-packages/matplotlib/_api/deprecation.py:196: in emit_warning
    warn_deprecated(
/opt/mambaforge/envs/mnedev/lib/python3.12/site-packages/matplotlib/_api/deprecation.py:99: in warn_deprecated
    warn_external(warning, category=MatplotlibDeprecationWarning)
/opt/mambaforge/envs/mnedev/lib/python3.12/site-packages/matplotlib/_api/__init__.py:381: in warn_external
    warnings.warn(message, category, stacklevel)
E   matplotlib._api.deprecation.MatplotlibDeprecationWarning: The interactive_bk attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin(matplotlib.backends.BackendFilter.INTERACTIVE)`` instead.
```

2024-12-10 16:55 UTC, cbrnr commented
Thanks @drammock. So what do we do? The issue is half a year old and it doesn't look like it's on the top of their to do list

2024-12-10 17:08 UTC, drammock commented
> Thanks @drammock. So what do we do? The issue is half a year old and it doesn't look like it's on the top of their to do list

IDK.  I forked and patched debugpy locally, but haven't yet managed to get [the debugpy *extension*](https://github.com/microsoft/vscode-python-debugger) to use the local, patched copy.

In the meantime, if instead of a breakpoint you add a `1/0` or `raise RuntimeError` or similar, then the "right-click -> debug test" works as expected (for me at least)

2024-12-10 17:11 UTC, larsoner commented
> Debugging tests work in other projects, so I was assuming that it's something specific to MNE. 

It probably is due to our treating all uncaught warnings as errors. If you add a line to our exceptions [here](https://github.com/mne-tools/mne-python/blob/730358c1e2e17baf0491c04e0c8269382a29c613/mne/conftest.py#L180) like:
```
    ignore:.*The interactive_bk attribute was deprecated:
```
Does it work? On at least get to another warning you could ignore?

2024-12-10 17:21 UTC, larsoner commented
>    ignore:The interactive_bk attribute was deprecated.*:MatplotlibDeprecationWarning

I would naively expect this to be problematic because `MatplotlibDeprecationWarning` is not a fully qualified name or builtin, so the test suite shouldn't even run IIRC (might be what your error means, you might see it if you run `pytest` yourself?). You should need:
```
    ignore:The interactive_bk attribute was deprecated.*:matplotlib._api.deprecation.MatplotlibDeprecationWarning
```
Or similar.

2024-12-10 17:38 UTC, drammock commented
> I would naively expect this to be problematic

ah, of course.

in the end I had to capture another similar warning too:

```py
    # debugpy uses deprecated matplotlib API
    ignore:The (non_)?interactive_bk attribute was deprecated.*:
```

2024-12-10 17:39 UTC, drammock commented
@cbrnr I just pushed the fix to this branch. Debugging should hopefully work correctly for you now.

2024-12-10 22:28 UTC, mscheltienne commented
I've been hitting this issue on VSCode for a while, ignoring the error in the conftest.py is my go-to solution. I think it's present in the conftest.py of MNE-LSL for instance.

2024-12-11 06:46 UTC, cbrnr commented
Thanks everyone for your help, I am really happy that I can debug tests again! I've included the warning as suggested and expanded the examples prose a bit, so this should be ready.

2024-12-11 20:00 UTC, drammock requested changes

2024-12-11 21:02 UTC, cbrnr commented on mne/io/base.py
> +                if ch_type not in self.get_channel_types():
Good catch, I'll change this tomorrow!

2024-12-13 10:11 UTC, cbrnr commented on mne/io/base.py
> +                if ch_type not in self.get_channel_types():
Done!

2024-12-13 14:45 UTC, drammock approved these changes
LGTM. My only hesitation is the param name `scale`, which is basically identical to what elsewhere we (I think?) consistently call `scalings`. To me `scale` is not obviously clearer (here or elsewhere) so its only advantage (I think?) is fewer characters. What do others think?

2024-12-13 14:55 UTC, drammock commented
> I do not really have a preference, but `scalings` is plural, which is a bit awkward when rescaling with a single factor (e.g. `raw.rescale(scalings=1e-6)`).

yeah that occurred to me, but the converse is also true (singular param name when passing a dict with multiple scaling values)

2024-12-13 15:12 UTC, larsoner commented
I think `scalings` is probably more consistent with what we do elsewhere

2024-12-13 15:32 UTC, cbrnr commented
I'll change it to `scalings` then.

2024-12-13 15:58 UTC, drammock approved these changes

2024-12-14 23:19 UTC, merged