Make concatenate_epochs work with empty Epochs objects
mne-tools/mne-python pull request #9535
Opened 2021-07-07 20:02 UTC by wmvanvliet

There was an edge case when concatenating Epochs and one (or more) of the `Epochs` objects was empty. See #9533.

fixes #9533

2021-07-07 20:05 UTC, wmvanvliet commented
This PR also redoes the logic of the `_update_offset` function which I found very confusing. Do you agree with this new implementation @larsoner?

2021-07-08 12:22 UTC, larsoner commented on mne/epochs.py
> +            else:
We probably always want to warn, not just when `add_offset == True`, so probably this is better structured as:
```
if len(evs) == 0:
    warn(...)
elif add_offset:
    ...
```

2021-07-08 12:32 UTC, larsoner commented
... and agreed the old logic didn't make much sense. No reason to track the offset when it's not being added!

2021-07-09 12:31 UTC, larsoner approved these changes
Can you add a `latest.inc` update in the BUG section? Then let's merge!

2021-07-09 12:31 UTC, larsoner commented
... except CIs appear unhappy:
```
mne/tests/test_epochs.py:2706: in test_concatenate_epochs
    concatenate_epochs([epochs, epochs2])
<decorator-gen-237>:24: in concatenate_epochs
    ???
mne/epochs.py:3451: in concatenate_epochs
    return _finish_concat(*_concatenate_epochs(epochs_list,
mne/epochs.py:3364: in _concatenate_epochs
    events_offset += int(np.max(evs[:, 0])) + shift
<__array_function__ internals>:5: in amax
    ???
/usr/share/miniconda/envs/mne/lib/python3.9/site-packages/numpy/core/fromnumeric.py:2754: in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
/usr/share/miniconda/envs/mne/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
E   ValueError: zero-size array to reduction operation maximum which has no identity
```

2021-07-09 12:32 UTC, larsoner requested changes
(Just changing to "request changes" until CIs and latest.inc are taken care of)

2021-07-11 11:35 UTC, wmvanvliet commented
I was being stubborn and broke the logic. Now I just took the approach you suggested and everything is working again :)

2021-07-12 13:11 UTC, merged

2021-07-12 13:12 UTC, larsoner commented
Thanks @wmvanvliet !